In [4]:
i=0
while i!=5:
    print("계속")
    i+=1
print("중단")

계속
계속
계속
계속
계속
중단


In [5]:
import numpy as np

In [6]:
mat_1=[[1,2],[3,4]]
mat_2=[[5,6],[7,8]]

In [7]:
result=np.array(mat_1)+np.array(mat_2)
print(result)

[[ 6  8]
 [10 12]]


In [8]:
import pandas as pd

In [9]:
x=pd.Series([1,2,3])
y=pd.Series([4,5,6])
z=pd.Series([7,8,9])

In [14]:
pd.concat([x,y,z],ignore_index=True,axis=1)

0  1  2
0  1  4  7
1  2  5  8
2  3  6  9

In [15]:
np.array(1)

array(1)

In [20]:
x=np.array([[1,2,3],[4,5,6]])
x[0][1]

2

In [21]:
data=[1,2,3,4,5,6,7,8,9,10]
count=0
for d in data:
    if d%5==0:
        count+=1

In [22]:
print(count)

2


In [23]:
count=0
for i in range(10):
    for j in range(5):
        count+=1
    count-=1
print(count)

40


In [38]:
count=0
for i in range(10):
    for j in range(5):
        count+=1
    count-=1
print(count)

40


In [24]:
data=[i*10 for i in range(100)]
len(data)

100

In [25]:
x=np.array([4,8,6]).reshape(3,1)
x

array([[4],
       [8],
       [6]])

In [27]:
y=np.arange(2,4)
y

array([2, 3])

In [28]:
x+y

array([[ 6,  7],
       [10, 11],
       [ 8,  9]])

In [33]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)