## 문제 1 
numpy 패키지를 임포트 하세요

In [2]:
import numpy as np

## 문제 2

numpy 버전을 출력하세요

In [3]:
import numpy
print(numpy.__version__)

1.20.3


In [42]:
#answer
np.__version__

'1.20.3'

## 문제 3

크기가 10인 zero vector Z 를 만드세요


In [44]:
a=np.zeros([10])
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 문제 4

위에서 만든 zero vector의 5번째 값을 1로 수정하시오

In [46]:
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 문제 5

10에서 49까지 범위의 값을 갖는 벡터 Z를 만드세요

In [47]:
Z=np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#문제 6

위에서 만든 벡터 Z를 역순으로 만드세요

In [48]:
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 문제 7


arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 의 벡터에서 홀수를 모두 -1로 바꾸세요

In [23]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
for i in arr:
    if i%2!=0:
        arr[i]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [51]:
#answer
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2==1]=-1
arr
#arr[조건]: 해당 조건을 만족하는 새로운 벡터(arr 변경)
#arr이 바뀜

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 문제 8
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 의 벡터에서 홀수를 모두 -1인 새로운 벡터를 만드세요

In [54]:
#answer_where활용
arr=np.array([0,1,2,3,4,5,6,7,8,9])
print(np.where(arr%2==1,-1,arr))
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


## 문제 9

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  벡터를 2x5 행렬로 바꾸세요

In [55]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr=arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 문제 10
```
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)
```
a 와 b를 아래와 같이 행 기준으로 합치세요
```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

In [80]:
#my
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
#answer
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)
print(np.concatenate([a,b]))
print(np.vstack([a,b]))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 문제 11
```
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
```

a와 b를 아래와 같이 열 기준으로 합치세요
```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

```



In [58]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)
print(np.concatenate([a,b], axis=1))
print(np.hstack([a,b]))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## 문제 12

0에서 8의 값을 갖는 3x3 행렬을 만드세요


In [31]:
#my
a=np.random.randint(0,9,size=(3,3))
a

array([[0, 5, 1],
       [5, 8, 1],
       [6, 3, 7]])

In [59]:
#answer
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 문제 13

다음과 같은 행렬 [1,2,0,0,4,0] 에서 0이 아닌 값의 인덱스를 찾으세요 

In [16]:
##다시 풀기
a=np.array([1,2,0,0,4,0])
np.where(a!=0)

(array([0, 1, 4], dtype=int64),)

In [60]:
##구글링_nonzero로 0이 아닌 값의 인덱스 찾기
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

## 문제 14

3x3 크기를 가지는 단위 행렬을 만드세요

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 문제 15

shape가 (3, 3, 3)인 랜덤값을 가지는 3차원 행렬을 만드세요

In [61]:
np.random.rand(3,3,3)

array([[[0.06336157, 0.98998346, 0.12915639],
        [0.25328546, 0.03200349, 0.2373181 ],
        [0.49868449, 0.05021336, 0.06525477]],

       [[0.26143227, 0.60518778, 0.65713911],
        [0.72414212, 0.59589238, 0.0473429 ],
        [0.44343056, 0.50082144, 0.83289207]],

       [[0.5681789 , 0.15662908, 0.81671593],
        [0.31059497, 0.56194218, 0.71110681],
        [0.00129266, 0.48574457, 0.79414761]]])

## 문제 16

Create a 10x10 array with random values and find the minimum and maximum
values

임의의 값으로 채워진 10x10 행렬을 만들고 그 행렬의 최소값과 최대값을 찾으세요.

In [69]:
#answer random.random
x=np.random.random(10)
print(x)
print(x.max())
print(x.min())

[0.7872335  0.60248991 0.51649275 0.98882239 0.32992767 0.30792694
 0.57885646 0.55761195 0.25634336 0.86242689]
0.9888223937200304
0.25634336046944783


## 문제 17

Create a random vector of size 30 and find the mean value

크기가 30인 임의의 벡터를 만들고 평균값을 찾으세요.

In [67]:
x=np.random.random(30)
print(x)

print(np.mean(x))
print(x.mean())

[0.82518275 0.76638995 0.58418624 0.57272491 0.74953976 0.42957105
 0.0589325  0.79189343 0.68624759 0.57731547 0.78034823 0.62605381
 0.57122139 0.65002543 0.89777057 0.4619503  0.43049859 0.57005944
 0.55784589 0.31767744 0.88384794 0.12878884 0.49320752 0.55238307
 0.08563241 0.70425055 0.18111883 0.39221277 0.87189517 0.14419092]
0.5447654260573092
0.5447654260573092


## 문제 18

Create a 2d array with 1 on the border and 0 inside

테두리가 1이고 내부가 0으로 채워진 2차원 행렬을 만드세요.

In [74]:
###구글링
z=np.ones((10,10))
z[1:-1,1:-1]=0  #슬라이싱으로 내부 가져오기
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 문제 19

What is the result of the following expression? 

다음 연산의 결과는 유추하세요.

In [76]:
#문제
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

#numpy의 nan = 파이썬의 none

nan
False
False
nan
False


## 문제 20

Create a vector of size 10 with values ranging from 0 to 1, both excluded

0에서 1 사이에 균등하게 배분된 값을 반환하는 벡터를 생성합니다(0, 1을 포함)

그 다음 처음과 마지막값을 제외한 배열을 출력하세요(출력하는 배열의 크기는 10입니다.).

In [79]:
#answer
a=np.linspace(0,1,12)[1:-1]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

## 문제 21

Create a random vector of size 10 and sort it

크기가 10인 임의의 벡터를 만들고 정렬하세요.

In [83]:
v=np.random.random(10)
v.sort()
v

array([0.15998809, 0.19420631, 0.23251183, 0.25770493, 0.29604719,
       0.36889489, 0.41175725, 0.42654541, 0.60249527, 0.71512434])

## 문제 22

Create random vector of size 10 and replace the maximum value by 0

크기가 10인 임의의 벡터를 만들고 최대값을 0으로 바꾸세요.

In [84]:
#my
v=np.random.random(10)
a=np.argmax(v)
v[a]=0
v

array([0.01368009, 0.82636743, 0.34242467, 0.81016474, 0.91446672,
       0.92526577, 0.73871263, 0.16753722, 0.89832375, 0.        ])

In [85]:
#answer
v=np.random.random(10)
print(v)
v[v.argmax()]=0
print(v)

[0.42413706 0.44340115 0.47272609 0.6434763  0.19062038 0.917879
 0.27617966 0.81483093 0.82826682 0.51286455]
[0.42413706 0.44340115 0.47272609 0.6434763  0.19062038 0.
 0.27617966 0.81483093 0.82826682 0.51286455]



## 문제 23

```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

```

a, b 두 벡터의 같은 위치에 있는 값이 같은 인덱스를 구하세요
```
결과 예)
(array([1, 3, 5, 7]),)
```

In [41]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.where(a==b))

(array([1, 3, 5, 7], dtype=int64),)


## 문제 24

```
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

a 에서 5이상 10 이하의 값만 가지는 벡터를 만드세요


In [3]:
#my
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5)&(a<=10)]

array([ 6,  9, 10])

In [86]:
#answer
a = np.array([2, 6, 1, 9, 10, 3, 27])
idx=np.where((a>=5) & (a<=10))
a[idx]

array([ 6,  9, 10])

In [ ]:
#Numpy 문제 모음 링크:
#https://u-n-joe.tistory.com/94?category=931569